import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Disclaimer | QuickCap',
    description: "Read the disclaimer for QuickCap. Understand the limitations and liabilities of using our AI-powered video captioning service. Information is provided 'as is'.",
    keywords: [
        'QuickCap disclaimer',
        'limitation of liability',
        'accuracy of information',
        'service disclaimer',
        'no warranties',
        'AI captioning disclaimer',
    ],
};

export default function DisclaimerPage() {
  return (
    <div className="py-12 md:py-20 lg:py-24">
      <div className="container mx-auto px-4">
        <div className="max-w-3xl mx-auto">
          <h1 className="font-headline text-4xl md:text-5xl font-bold">Disclaimer</h1>
          <p className="text-muted-foreground mt-2">Last updated: August 04, 2025</p>
          
          <div className="space-y-8 mt-8 text-foreground/90">
            <div>
              <h2 className="font-headline text-2xl font-bold mt-8 mb-2">1. Accuracy of Information</h2>
              <p>
                The captions and translations generated by QuickCap are created by an automated AI system. While we strive for high accuracy, we cannot guarantee that the information provided by our service will be completely accurate, reliable, or timely. The quality of the output is heavily dependent on the quality of the source audio.
              </p>
            </div>

            <div>
              <h2 className="font-headline text-2xl font-bold mt-8 mb-2">2. No Warranties</h2>
              <p>
                The service is provided on an "as is" and "as available" basis. QuickCap makes no warranties, expressed or implied, regarding the operation of the service or the information, content, or materials included therein. You expressly agree that your use of the service is at your sole risk.
              </p>
            </div>

            <div>
              <h2 className="font-headline text-2xl font-bold mt-8 mb-2">3. Limitation of Liability</h2>
              <p>
                In no event shall QuickCap, its directors, employees, or agents be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising out of your use of, or inability to use, the service. This includes damages for errors, omissions, interruptions, defects, delays, computer viruses, loss of profits, loss of data, unauthorized access to and alteration of your transmissions and data, and other tangible and intangible losses.
              </p>
            </div>

            <div>
                <h2 className="font-headline text-2xl font-bold mt-8 mb-2">4. External Links</h2>
                <p>
                    Our service may contain links to external websites that are not provided or maintained by or in any way affiliated with QuickCap. Please note that we do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.
                </p>
            </div>

            <div>
              <h2 className="font-headline text-2xl font-bold mt-8 mb-2">5. Professional Advice</h2>
              <p>
                The information provided by QuickCap is for general informational purposes only and is not a substitute for professional advice. You should not act or refrain from acting on the basis of any content included in the service without seeking the appropriate legal or other professional advice on the particular facts and circumstances at issue.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
